### PR TITLE
Arabic language support

### PR DESCRIPTION
**Pull request by mahmodmasoud2009**
## Type of change

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring 
- [ ] Documentation content changes

<br><br>

## Description

Adding Arabic language support 

cropped

### CODE REVIEW

**Comment by kattaliraees** [comment]
@mincheol-shin could you please check this PR?

**Comment by mincheol-shin** [comment]
Thank you so much for your contribution!

**Review by mincheol-shin — APPROVED** [review]

**Comment by mahmodmasoud2009** [comment]
You are welcome. Will you be publishing a new version in pub.dev soon ?

**Comment by mincheol-shin** [comment]
We added the function and proceeded with the 3.7.1 update.

Thank you.

**Pull request merged**
